services:
  # Product Service
  - type: web
    name: product-service
    env: docker
    dockerfilePath: ./backend/product-service/Dockerfile
    dockerContext: ./backend/product-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # Order Service
  - type: web
    name: order-service
    env: docker
    dockerfilePath: ./backend/order-service/Dockerfile
    dockerContext: ./backend/order-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # User Service
  - type: web
    name: user-service
    env: docker
    dockerfilePath: ./backend/user-service/Dockerfile
    dockerContext: ./backend/user-service
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

  # API Gateway
  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./backend/api-gateway/Dockerfile
    dockerContext: ./backend/api-gateway
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PRODUCT_SERVICE_URL
        value: https://product-service.onrender.com
      - key: ORDER_SERVICE_URL
        value: https://order-service.onrender.com
      - key: USER_SERVICE_URL
        value: https://user-service.onrender.com

  # Frontend (Static Site)
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://api-gateway.onrender.com
